services:
  authdb-prod:
    container_name: authdb-prod
    image: postgres:17
    environment:
      - POSTGRES_USER=tacauthuser
      - POSTGRES_PASSWORD=tacauthpass
      - POSTGRES_DB=tacauthdb
      - PGDATA=/authdb-prod/data/postgres
    volumes:
      - authdb_data:/var/docker/taccaseapi
      - ./db_init:/docker-entrypoint-initdb.d
    ports:
      - 6432:5432
    networks:
      - backend
    #    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 10s
      timeout: 3s
      retries: 3
    profiles:
      - production

  authsvr-prod:
    container_name: authsvr-prod
    image: pbranestrategy/tac-case-api-auth-server:0.1.3
    environment:
      - CLIENT_ID=client-id
      - CLIENT_SECRET=client-secret
      - CLIENT_NAME=client-name
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://authdb-prod:5432/tacauthdb
      - SPRING_DATASOURCE_USERNAME=tacauthuser
      - SPRING_DATASOURCE_PASSWORD=tacauthpass
      - AUTH_SVR_ENV=production
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - 9080:8080
    depends_on:
      authdb-prod:
        condition: service_healthy
    networks:
      - backend
#    restart: unless-stopped
    profiles:
      - production

  authsvr-dev:
    container_name: authsvr-dev
    image: pbranestrategy/tac-case-api-auth-server:0.1.3
    environment:
      - CLIENT_ID=client-id
      - CLIENT_SECRET=client-secret
      - CLIENT_NAME=client-name
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://authdb-dev:5432/tacauthdb
      - SPRING_DATASOURCE_USERNAME=tacauthuser
      - SPRING_DATASOURCE_PASSWORD=tacauthpass
      - AUTH_SVR_ENV=development
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - 9080:8080
#    depends_on:
#      authdb-dev:
#        condition: service_healthy
    networks:
      - backend
#    restart: unless-stopped
    profiles:
      - development

networks:
  backend:
    driver: bridge

volumes:
  authdb_data:

